name: Deploy Locadora

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.JS ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - run: npm i
      - run: npm run test
  build:
    needs: test
    runs-on: self-hosted
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Docker up
        env:
          PORT: ${{ secrets.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          VIRTUAL_HOST: ${{ secrets.VIRTUAL_HOST }}
          DEFAULT_HOST: ${{ secrets.DEFAULT_HOST }}
        run: sudo docker-compose down && sudo docker-compose up -d --build --remove-orphans --force-recreate
