name: Deploy Locadora

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.JS ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: npm i
      - run: npm run test
